name: Stale Issues and PRs
on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:
    inputs:
      dryRun:
        description: Set to true for a dry run
        required: false
        default: "false"
        type: string

jobs:
  stale_workflow:
    permissions:
      issues: write
      pull-requests: write
    uses: turbot/steampipe-workflows/.github/workflows/stale.yml@210ab7cc3f105a795a389cf30d68c394ee46af5e # main @ 2026-07-29
    with:
      dryRun: ${{ github.event.inputs.dryRun }}
