name: Sync Labels
on:
  schedule:
    - cron: "30 22 * * 1"
  workflow_dispatch:

jobs:
  sync_labels_workflow:
    permissions:
      issues: write
    uses: turbot/steampipe-workflows/.github/workflows/sync-labels.yml@210ab7cc3f105a795a389cf30d68c394ee46af5e # main @ 2026-07-29
